### ISSUE TITLE
Add lives and score to Player

### ISSUE THREAD

**Issue by wpoynter** [grizzly-studios/Space-Evaders#67]
The Player object should hold the lives and score. We should also add the following associated functions:
- 1up                    #adds a life
- 1down               #take a life
- hit                       #calls 1down and causes the player to be immune when we can add that
- kill                       #remove all lives
- score(value)     #add value to score total
- score(void)       #returns score
- penalty(value)  #This is optional, to lower score by value, but we could just use score with a negative value

**Comment by jademonkey** [comment]
created f_adv-player to handle this
