### ISSUE TITLE
[Minor] Unnecessary warning message on startup

### ISSUE THREAD

**Issue by jademonkey** [grizzly-studios/Space-Evaders#69]
As part of PR #66 i'm now seeing the following warning message on startup:

[07/04/2015 22:33:02] - WARN - src/main/app/Application.cpp:67 - Unknown Flag: dew

I've started the game with the flags -v dew. 

Looks like after we parse the logging settings we forget to not check them afterwards.

**Comment by wpoynter** [comment]
Can you give a screenshot of the bug?

**Comment by jademonkey** [comment]
![bug](https://cloud.githubusercontent.com/assets/5496935/7330185/9949a90c-eae1-11e4-80a6-342c1da8ed44.png)

**Comment by jademonkey** [comment]
Ok realised what i was doing wrong. I thought the way to minimize the logging was to do something like "-v dew" when after reading code i realise you do "-v=dew"
